name: Linux3ui-auto
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TUNNEL_URL: ""
      Config_URL: ""
      SSH_URL: ""
      USERNAME: ""
      PASSWORD: ""
      WEBBASEPATH: ""
      MyConfig1: ""
      MyConfig2: ""
    steps:
      - name: Set And Create EVN
        run: |
          echo "VFVOTkVMX1VSTD0iIgpDb25maWdfVVJMPTwiIgpTU0hfVVJMPTwiIgpVU0VSTkFNRT0iIgpQQVNTV09SRD0iIldFQkJBU0VQVEg9IiIKZWNobyAiJFRVTk5FTF9VUkwiID4gdHVubmVsX3VybC50eHQKZWNobyAiJENvbmZpZ19VUkwiID4gY29uZmlnX3VybC50eHQKZWNobyAiJFVTRVJOQU1FIiA+IHVzZXJuYW1lX3VybC50eHQKZWNobyAiJFBBU1NXT1JEIiA+IHBhc3NfdXJsLnR4dAp" | base64 -d | bash

      - name: Update and install packages
        run: |
          echo "c3VkbyBhcHQtZ2V0IHVwZGF0ZSAtcXEKc3VkbyBhcHQtZ2V0IGluc3RhbGwgLXkgbmVvZmV0Y2ggc3BlZWR0ZXN0LWNsaSBwaHAtY2xpIGN1cmw=" | base64 -d | bash

      - name: Download sshd_config
        run: |
          echo "d2dldCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vR29nb1ppbi9zc2hkL21haW4vc3NoZF9jb25maWcgLU8gc3NoZF9jb25maWc=" | base64 -d | bash

      - name: Replace sshd_config
        run: |
          echo "c3VkbyBjcCBzc2hkX2NvbmZpZyAvZXRjL3NzaC9zc2hkX2NvbmZpZw==" | base64 -d | bash

      - name: Restart SSH service
        run: |
          echo "c3VkbyBzZXJ2aWNlIHNzaCByZXN0YXJ0" | base64 -d | bash

      - name: Remove root password
        run: |
          echo "c3VkbyBwYXNzd2QgLWQgcm9vdA==" | base64 -d | bash

      - name: Remove runner password
        run: |
          echo "c3VkbyBwYXNzd2QgLWQgcnVubmVy" | base64 -d | bash

      - name: Start Panel Tunnel
        run: |
          echo "d2dldCBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jbG91ZGZsYXJlZC9yZWxlYXNlcy9sYXRlc3QvZG93bmxvYWQvY2xvdWRmbGFyZWQtbGludXgtYW1kNjQgLU8gcGFuZWx0dW5uZWwtcnVubmVyCmNwIHBhbmVsdHVubmVsLXJ1bm5lciBjb25maWd0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggcGFuZWx0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggY29uZmlndHVubmVsLXJ1bm5lcgpub2h1cCAuL3BhbmVsdHVubmVsLXJ1bm5lciB0dW5uZWwgLS11cmwgaHR0cDovL2xvY2FsaG9zdDoyMDUzIC0tbm8tdGxzLXZlcmlmeSAtLW5vLWF1dG91cGRhdGUgLS1lZGdlLWlwLXZlcnNpb24gYXV0byAtLXByb3RvY29sIGh0dHAyID4gcGFuZWx0dW5uZWwubG9nIDI+JjEgJiAgICAgCmZvciBpIGluIHsxLi4xOH07IGRvCmVjaG8gIkZvdW5kIENyZWF0ZWQgVHVubmVsIC0gVHJheSAkaSAuLi4iClRVTk5FTF9VUkw9JChncmVwIC1vICdodHRwczovL1teIF0qXC50cnljbG91ZGZsYXJlXC5jb20nIHBhbmVsdHVubmVsLmxvZyB8IHRhaWwgLW4gMSkKCmlmIFsgLW4gIiRUVU5ORUxfVVJMIiBdOyB0aGVuCiBlY2hvICLinIUgUGFuZWwgVHVubmVsIENyZWF0ZWQhIgogZWNobyAiUGFuZWxUdW5uZWwgQWRkcmVzczogJFRVTk5FTF9VUkwiCiBlY2hvICIkVFVOTkVMX1VSTCIgPiB0dW5uZWxfdXJsLnR4dAogYnJlYWsKZmkKIHNsZWVwIDEwCmRvbmU=" | base64 -d | bash

      - name: Start Config Tunnel
        run: |
          echo "bm9odXAgLi9jb25maWd0dW5uZWwtcnVubmVyIHR1bm5lbCAtLXVybCBodHRwOi8vbG9jYWxob3N0OjEyODAgLS1uby1hdXRvdXBkYXRlIC0tZWRnZS1pcC12ZXJzaW9uIGF1dG8gLS1wcm90b2NvbCBodHRwMiA+IGNvbmZpZ3R1bm5lbC5sb2cgMj4mMSAmCmZvciBpIGluIHsxLi4xOH07IGRvCmVjaG8gIkZvdW5kIENyZWF0ZWQgVHVubmVsIC0gVHJheSAkaSAuLi4iCkNvbmZpZ19VUkw9JChncmVwIC1vICdodHRwczovL1teIF0qXC50cnljbG91ZGZsYXJlXC5jb20nIGNvbmZpZ3R1bm5lbC5sb2cgfCB0YWlsIC1uIDEgfCBzZWQgJ3N8Xmh0dHBzOi8vfHwnKQoKaWYgWyAtbiAiJENvbmZpZ19VUkwiIF07IHRoZW4KIGVjaG8gIuKchSBDb25maWcgVHVubmVsIENyZWF0ZWQhIgogZWNobyAiQ29uZmlnVHVubmVsIEFkZHJlc3M6ICRDb25maWdfVVJMIgogZWNobyAiJENvbmZpZ19VUkwiID4gY29uZmlnX3VybC50eHQKIGJyZWFrCmZpCiBzbGVlcCAxMApkb25l" | base64 -d | bash

      - name: Start Panel Tunnel (Cloudflare)
        run: |
          echo "d2dldCBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jbG91ZGZsYXJlZC9yZWxlYXNlcy9sYXRlc3QvZG93bmxvYWQvY2xvdWRmbGFyZWQtbGludXgtYW1kNjQgLU8gcGFuZWx0dW5uZWwtcnVubmVyCmNwIHBhbmVsdHVubmVsLXJ1bm5lciBjb25maWd0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggcGFuZWx0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggY29uZmlndHVubmVsLXJ1bm5lcgpub2h1cCAuL3BhbmVsdHVubmVsLXJ1bm5lciB0dW5uZWwgLS11cmwgaHR0cDovL2xvY2FsaG9zdDoyMDUzIC0tbm8tdGxzLXZlcmlmeSAtLW5vLWF1dG91cGRhdGUgLS1lZGdlLWlwLXZlcnNpb24gYXV0byAtLXByb3RvY29sIGh0dHAyID4gcGFuZWx0dW5uZWwubG9nIDI+JjEgJgpmb3IgaSBpbiB7MS4uMTh9OyBkbwplY2hvICJGb3VuZCBDcmVhdGVkIFR1bm5lbCAtIFRyYXkgJGkgLi4uIgpUVU5ORUxfVVJMPWdyZXAgLW8gJ2h0dHBzOi8vW14gXSpcLnRyeWNsb3VkZmxhcmUuY29tJyBwYW5lbHR1bm5lbC5sb2cgfCB0YWlsIC1uIDEKaWYgWyAtbiAiJFRVTk5FTF9VUkwiIF07IHRoZW4KZWNobyAi4piGIFBhbmVsIFR1bm5lbCBDcmVhdGVkISIKZWNobyAiUGFuZWxUdW5uZWwgQWRkcmVzczogJFRVTk5FTF9VUkwiCmVjaG8gIiRUVU5ORUxfVVJMIiA+IHR1bm5lbF91cmwudHh0CmJyZWFrCmZpCnNsZWVwIDEwCmRvbmU=" | base64 -d | bash

      - name: Start Config Tunnel
        run: |
          echo "bm9odXAgLi9jb25maWd0dW5uZWwtcnVubmVyIHR1bm5lbCAtLXVybCBodHRwOi8vbG9jYWxob3N0OjEyODAgLS1uby1hdXRvdXBkYXRlIC0tZWRnZS1pcC12ZXJzaW9uIGF1dG8gLS1wcm90b2NvbCBodHRwMiA+IGNvbmZpZ3R1bm5lbC5sb2cgMj4mMSAmCg==" | base64 -d | bash

      - name: Show Info
        run: |
          echo "VFVOTkVMX1VSTD0kKGNhdCB0dW5uZWxfdXJsLnR4dCkKQ29uZmlnX1VSTD0kKGNhdCBjb25maWdfdXJsLnR4dCkKU1NIX1VSTD0kKGNhdCBzc2hfdXJsLnR4dCkKVVNFUk5BTUU9JChjYXQgdXNlcm5hbWVfdXJsLnR4dCkKUEFTU1dPUkQ9JChjYXQgcGFzc191cmwudHh0KQpXRUJCQVNFUEFUSD0iL1phMHp0djdZM0NKREhUNVFxcCIKTXlDb25maWcxPSJ2bGVzczovLzQyZDM0ZmVjLTNhYWQtNDg0Ny04YzI5LWIwZjBkOGUxZGNiZkAkQ29uZmlnX1VSTDo0NDM/ZW5jcnlwdGlvbj1ub25lJnNlY3VyaXR5PXRscyZzbmk9JENvbmZpZ19VUkwmYWxsb3dJbnNlY3VyZT10cnVlJmFscG49aHR0cC8xLjEmZnA9Y2hyb21lJnR5cGU9d3MmaG9zdD0kQ29uZmlnX1VSTCZwYXRoPS9hM09wdEtUTktJNklDWWlSQ3Q1JnBhY2tldEVuY29kaW5nPXh1ZHAj4pim4q2Q77iPTWFzdGVyVmlwIgpNeUNvbmZpZzI9InZsZXNzOi8vNDJkMzRmZWMtM2FhZC00ODQ3LThjMjktYjBmMGQ4ZTFkY2JmQHd3dy5zcGVlZHRlc3QubmV0OjQ0Mz9lbmNyeXB0aW9uPW5vbmUmc2VjdXJpdHk9dGxzJnNuaT0kQ29uZmlnX1VSTCZhbGxvd0luc2VjdXJlPXRydWUmYWxwbj1odHRwLzEuMSZmcD1jaHJvbWUmdHlwZT13cyZob3N0PSRDb25maWdfVVJMKHBhdGg9L2EzT3B0S1ROS0k2SUNZaVJDdDUmcGFja2V0RW5jb2Rpbmc9eHVkcCNimKYg4q2Q77iPTWFzdGVyVmlwIgo=" | base64 -d | bash

      - name: Send message to Bale Group
        env:
          TOKEN: "1076637420:eGO9F9RO7kM27YetwEGIFyR316Bj0dERp9A"
          CHAT_ID: 5812315610
          USER_NAME: "Morteza_V2Ray Config"
        run: |
          echo "TXlDb25maWcxPSQoY2F0IG15Y29uZmlnMV91cmwudHh0KQpNeUNvbmZpZzI9JGNhdCBteWNvbmZpZzJfdXJsLnR4dApDVVJSRU5UX1RJTUU9JGRhdGUgIislWS8lYy8lZCBILVk6JUg6JVMiCgpkb3duY3VybCAtWCBQT1NUIAoaHR0cHM6Ly90YXBpLmJhbGUuYWkvJHtUT0tFTn0vc2VuZE1lc3NhZ2UpIC1IICJDb250ZW50LVR5cGU6IGFwcGxpY2F0aW9uL2pzb24iIC1kICJ7CiAgICAiY2hhdF9pZCI6ICInIiR7Q0hBVF9JRH0iJyIsCiAgICAidGV4dCI6ICInIiR7VVNFUl9OQU1FfScKXG5cbiIkTXlDb25maWcxXG5cbiIkTXlDb25maWcyXG5cbiIlwqAgJHtDVVJSRU5UX1RJTUUgfSJ9Ig==" | base64 -d | bash
      
      - name: Delay and Self-Restart (5 hours 25 minutes)
        env:
          PAT: ${{ secrets.PAT_WORKFLOW }}
          REPO: ${{ github.repository }}
        run: |
          echo "ZWNobyAi4pGbIFN0YXJ0aW5nIGRlbGF5IHRpbWVyczogNSBob3VycyBhbmQgMjUgbWludXRlcy4uLiIKZWNobyAiIEN1cnJlbnQgdGltZTogJChkYXRlKSIKc2xlZXAgMTk1MDAKZWNobyAi8J+RiCBUaHJpZ2dlcmluZyB3b3JrZmxvdyByZXN0YXJ0Li4uIgpjdXJsIC1YIFBPU1QgXAogIC1IICJBY2NlcHQ6IGFwcGxpY2F0aW9uL3ZuZC5naXRodWIuMCtqc29uIiBcCiAgLUggIkF1dGhvcml6YXRpb246IHRva2VuICRQQVQiIAogaHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy8kUkVQTy9hY3Rpb25zL3dvcmtmbG93cy9NeVNlcnZlckwxLnltbC9kaXNwYXRjaGVzIC1kICcie3JlZjoi bWFpbiJ9JwplY2hvICLwn5GgIFJlc3RhcnQgY29tbWFuZCBzZW50IHN1Y2Nlc3NmdWxseSBhdCAkKGRhdGUpIg==" | base64 -d | bash

      - name: Keep alive
        run: tail -f /dev/null
