name: Auto Restart Worker

permissions:
  actions: write
  
on: 
  schedule:
    - cron: '*/15 * * * *'     # هر ۵ ساعت و ۵۰ دقیقه یکبار

  push:
  workflow_dispatch:           # برای تست دستی

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/LinuxServer_Tun.yml/dispatches \
            -d '{"ref":"main"}'
